.TH LIGHTCLI 3
.SH NAME
lightcli.get_input - Python function to ask for input and check its sanity.

.SH SYNOPSIS
    \fBimport lightcli
    \fBlightcli.get_input(\fR[options=\fI<options>\fR], [prompt=\fI<prompt>\fR], [qopt={\fITrue\fR|\fIFalse\fR}]\fB)\fR


.SH DESCRIPTION
\fBlightcli\fP is a lightweight terminal interaction library for Python.

.SH FUNCTIONS
\fBlightcli.get_input(\fR[options=\fI<options>\fR], [prompt=\fI<prompt>\fR], [qopt={\fITrue\fR|\fIFalse\fR}]\fB)\fR
    Prompts for and returns input. 'options' is the list of acceptable answers (a list of strings). 'prompt' is the text shown when asking for input (a string). 'qopt' toggles a 'q to quit' option (True/False: default is False).

.SH FILES
    /usr/share/doc/lightcli/README.md
    /usr/share/doc/lightcli/LICENSE

.SH AUTHOR
Dan Persons (dpersonsdev@gmail.com)

.SH COPYRIGHT
Copyright (C) 2017 Dan Persons (dpersonsdev@gmail.com)

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
